import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, FileText, Home, Menu, MessageSquareText, Moon, PanelLeftClose, Plus, Search, Settings, Sparkles, Sun, TrendingUp, Users } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { Logo } from "@/components/brand/logo";
import { useTheme } from "@/app/theme-provider";

const navigation = [
  { label:"Aujourd’hui", icon:Home }, { label:"Créer", icon:Sparkles }, { label:"Planifier", icon:CalendarDays },
  { label:"Mes contenus", icon:FileText }, { label:"Mes résultats", icon:TrendingUp }, { label:"Mon audience", icon:Users },
];
const recommendations = [
  { tag:"OPPORTUNITÉ", title:"Prolongez l’intérêt suscité hier", text:"Votre annonce produit génère 2,4× plus de conversations. Un retour d’expérience publié demain entre 8h et 9h devrait maintenir l’élan.", action:"Préparer le contenu", accent:"violet" },
  { tag:"RYTHME", title:"Votre semaine manque d’un temps fort", text:"Je vous propose une prise de parole plus personnelle jeudi, liée aux coulisses de l’équipe.", action:"Voir ma proposition", accent:"amber" },
  { tag:"À SURVEILLER", title:"LinkedIn progresse, Instagram ralentit", text:"Votre audience réagit mieux aux formats incarnés. J’ai identifié trois contenus à adapter.", action:"Comprendre pourquoi", accent:"blue" },
];

function Panel({children,className=""}:{children:ReactNode;className?:string}) { return <div className={`cos-card rounded-2xl ${className}`}>{children}</div> }

function CommandPalette({open,onClose}:{open:boolean;onClose:()=>void}) {
  const [query,setQuery]=useState("");
  const actions=useMemo(()=>["Créer un post LinkedIn","Préparer mon brief de la semaine","Analyser mes derniers résultats","Planifier une campagne","Trouver une idée de contenu"].filter(x=>x.toLowerCase().includes(query.toLowerCase())),[query]);
  return <AnimatePresence>{open&&<motion.div className="fixed inset-0 z-[80] flex justify-center bg-black/55 px-4 pt-[12vh] backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.div role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()} initial={{opacity:0,y:-12,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-8,scale:.98}} className="h-fit w-full max-w-2xl overflow-hidden rounded-3xl border border-white/10 bg-[#12131a] text-white shadow-2xl"><div className="flex items-center gap-3 border-b border-white/8 px-5"><Sparkles className="size-5 text-violet-400"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Que voulez-vous accomplir ?" className="h-16 flex-1 bg-transparent text-base outline-none placeholder:text-zinc-600"/><kbd className="rounded-md border border-white/10 px-2 py-1 text-[10px] text-zinc-500">ESC</kbd></div><div className="p-3"><p className="px-3 py-2 text-[10px] uppercase tracking-widest text-zinc-600">Demander à votre responsable communication</p>{actions.map((x,i)=><button key={x} className={`flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-sm hover:bg-white/7 ${i===0?"bg-white/7":""}`}><span><Sparkles className="mr-3 inline size-4 text-violet-400"/>{x}</span><span className="text-xs text-zinc-600">↵</span></button>)}<div className="mt-2 border-t border-white/8 px-3 pt-3 text-xs text-zinc-600">Essayez : « Que devrais-je publier cette semaine ? »</div></div></motion.div></motion.div>}</AnimatePresence>
}

export function DashboardPage() {
  const [palette,setPalette]=useState(false),[mobile,setMobile]=useState(false),[notice,setNotice]=useState(false),[profile,setProfile]=useState(false),[collapsed,setCollapsed]=useState(false),[toast,setToast]=useState(false);
  const {setTheme,resolvedTheme}=useTheme();
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}if(e.key==="Escape")setPalette(false)};addEventListener("keydown",handler);return()=>removeEventListener("keydown",handler)},[]);
  const sidebar=<><div className="flex h-16 items-center justify-between px-4"><Logo/>{!mobile&&<button onClick={()=>setCollapsed(!collapsed)} aria-label="Réduire la navigation" className="cos-muted"><PanelLeftClose className="size-4"/></button>}</div><div className="px-3"><button className="cos-card flex h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-sm"><span className="grid size-7 place-items-center rounded-lg bg-gradient-to-br from-violet-500 to-pink-400 text-xs text-white">AH</span>{!collapsed&&<><span className="flex-1">Atelier Horizon</span><ChevronDown className="size-3"/></>}</button></div><nav className="mt-5 px-3">{navigation.map(({label,icon:Icon},i)=><button key={label} className={`mb-1 flex h-10 w-full items-center gap-3 rounded-xl px-3 text-sm transition ${i===0?"bg-violet-500/10 text-violet-500":"cos-muted hover:bg-[var(--surface-2)] hover:text-[var(--ink)]"}`}><Icon className="size-4 shrink-0"/>{!collapsed&&label}</button>)}</nav><div className="mt-auto border-t border-[var(--line)] p-3"><button className="cos-muted flex h-10 w-full items-center gap-3 rounded-xl px-3 text-sm"><Settings className="size-4"/>{!collapsed&&"Réglages"}</button><div className="mt-2 flex items-center gap-3 px-3 py-2"><span className="grid size-8 place-items-center rounded-full bg-gradient-to-br from-orange-200 to-pink-300 text-xs font-semibold text-zinc-900">LM</span>{!collapsed&&<div className="min-w-0"><p className="truncate text-xs font-medium">Léa Martin</p><p className="cos-muted truncate text-[10px]">Administratrice</p></div>}</div></div></>;
  return <div className="min-h-screen bg-[var(--canvas)] text-[var(--ink)]"><CommandPalette open={palette} onClose={()=>setPalette(false)}/><AnimatePresence>{mobile&&<><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/50" onClick={()=>setMobile(false)}/><motion.aside initial={{x:-300}} animate={{x:0}} exit={{x:-300}} className="fixed inset-y-0 left-0 z-50 flex w-72 flex-col bg-[var(--surface)]">{sidebar}</motion.aside></>}</AnimatePresence>
    <aside className={`fixed inset-y-0 left-0 hidden flex-col border-r border-[var(--line)] bg-[var(--surface)] transition-all lg:flex ${collapsed?"w-[72px]":"w-[240px]"}`}>{sidebar}</aside>
    <div className={`transition-all ${collapsed?"lg:pl-[72px]":"lg:pl-[240px]"}`}><header className="sticky top-0 z-40 flex h-16 items-center gap-3 border-b border-[var(--line)] bg-[color-mix(in_srgb,var(--canvas)_84%,transparent)] px-4 backdrop-blur-xl sm:px-6"><button onClick={()=>setMobile(true)} className="lg:hidden"><Menu className="size-5"/></button><p className="hidden text-sm sm:block"><span className="cos-muted">Atelier Horizon /</span> Aujourd’hui</p><button onClick={()=>setPalette(true)} className="cos-card cos-muted mx-auto flex h-9 w-full max-w-sm items-center gap-2 rounded-xl px-3 text-left text-xs"><Search className="size-3.5"/>Demander ou rechercher…<kbd className="ml-auto rounded border border-[var(--line)] px-1.5 py-0.5 text-[10px]">⌘ K</kbd></button><div className="relative"><button onClick={()=>setNotice(!notice)} aria-label="Notifications" className="cos-card grid size-9 place-items-center rounded-xl"><Bell className="size-4"/><i className="absolute right-0 top-0 size-2 rounded-full bg-pink-500"/></button>{notice&&<Panel className="absolute right-0 top-12 w-80 bg-[var(--surface)] p-4 shadow-2xl"><p className="font-medium">Notifications</p><p className="cos-muted mt-4 text-sm">Votre calendrier de jeudi a été optimisé.</p><p className="cos-muted mt-3 text-sm">Le bilan de juin est disponible.</p></Panel>}</div><div className="relative"><button onClick={()=>setProfile(!profile)} className="grid size-9 place-items-center rounded-full bg-gradient-to-br from-orange-200 to-pink-300 text-xs font-semibold text-zinc-900">LM</button>{profile&&<Panel className="absolute right-0 top-12 w-56 bg-[var(--surface)] p-2 shadow-2xl"><p className="px-3 py-2 text-sm font-medium">Léa Martin</p><button onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")} className="cos-muted flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-[var(--surface-2)]">{resolvedTheme==="dark"?<Sun className="size-4"/>:<Moon className="size-4"/>}Mode {resolvedTheme==="dark"?"clair":"sombre"}</button><Link to="/" className="cos-muted block rounded-lg px-3 py-2 text-sm hover:bg-[var(--surface-2)]">Voir le site</Link></Panel>}</div></header>
      <main className="mx-auto max-w-[1480px] px-4 py-7 sm:px-7 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="cos-muted text-sm">Lundi 10 juillet · Semaine 28</p><h1 className="mt-1 text-3xl font-medium tracking-[-.04em] sm:text-4xl">Bonjour Léa, j’ai préparé votre journée.</h1></div><button onClick={()=>setPalette(true)} className="flex items-center justify-center gap-2 rounded-xl bg-[var(--ink)] px-4 py-3 text-sm text-[var(--canvas)]"><Sparkles className="size-4"/>Demander à l’IA</button></div>
        <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><p className="font-medium">Ce qui mérite votre attention</p><p className="cos-muted mt-1 text-sm">3 recommandations basées sur vos résultats et votre calendrier.</p></div><span className="hidden items-center gap-2 text-xs text-emerald-500 sm:flex"><i className="size-2 animate-pulse rounded-full bg-emerald-400"/>Analyse à jour</span></div><div className="grid gap-4 xl:grid-cols-3">{recommendations.map((r,i)=><motion.div key={r.title} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*.08}} className={`relative overflow-hidden rounded-2xl border p-5 ${i===0?"border-violet-500/25 bg-gradient-to-br from-violet-500/12 to-pink-400/5":"border-[var(--line)] bg-[var(--surface)]"}`}><div className="flex items-center justify-between"><span className="text-[10px] font-semibold tracking-widest text-violet-500">{r.tag}</span><span className="cos-muted text-[10px]">Confiance {94-i*5}%</span></div><h2 className="mt-5 text-lg font-medium">{r.title}</h2><p className="cos-muted mt-2 min-h-16 text-sm leading-6">{r.text}</p><button onClick={()=>{setToast(true);setTimeout(()=>setToast(false),2500)}} className="mt-5 text-sm font-medium text-violet-500">{r.action}<ArrowUpRight className="ml-1 inline size-3"/></button></motion.div>)}</div></section>
        <section className="mt-6 grid gap-4 lg:grid-cols-[1.45fr_.8fr]"><Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="font-medium">Votre communication prend de l’élan</p><p className="cos-muted mt-1 text-xs">Performance globale · 30 derniers jours</p></div><button className="cos-card rounded-lg px-3 py-2 text-xs">30 jours <ChevronDown className="ml-1 inline size-3"/></button></div><div className="mt-8 flex h-48 items-end gap-1 sm:gap-2">{[22,28,25,38,35,48,43,55,52,67,60,72,68,83,78,92,85,96].map((h,i)=><motion.div initial={{height:0}} whileInView={{height:`${h}%`}} viewport={{once:true}} transition={{delay:i*.025}} key={i} className="group relative flex-1 rounded-t-sm bg-gradient-to-t from-violet-500/30 to-violet-500 hover:to-pink-400"><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 rounded bg-zinc-900 px-2 py-1 text-[9px] text-white group-hover:block">{h}</span></motion.div>)}</div><div className="cos-muted mt-3 flex justify-between text-[10px]"><span>10 juin</span><span>20 juin</span><span>30 juin</span><span>10 juillet</span></div></Panel><Panel className="p-5 sm:p-6"><p className="font-medium">Le pouls de votre marque</p><p className="cos-muted mt-1 text-xs">Synthèse par votre IA</p><div className="mt-6 grid grid-cols-2 gap-3">{[["82","Score de présence","+12"],["6,8%","Engagement","+1,4"],["14","Contenus publiés","+3"],["91%","Cohérence de ton","Stable"]].map(([v,l,d])=><div className="rounded-xl bg-[var(--surface-2)] p-4"><p className="text-2xl font-medium">{v}</p><p className="cos-muted mt-1 text-[11px]">{l}</p><p className="mt-2 text-[10px] text-emerald-500">{d}</p></div>)}</div><p className="cos-muted mt-5 border-t border-[var(--line)] pt-4 text-xs leading-5"><Sparkles className="mr-2 inline size-3 text-violet-500"/>Votre régularité progresse. L’enjeu suivant est de mieux incarner vos prises de parole.</p></Panel></section>
        <section className="mt-6 grid gap-4 lg:grid-cols-[1.4fr_.8fr]"><Panel className="overflow-hidden"><div className="flex items-center justify-between p-5 sm:p-6"><div><p className="font-medium">Cette semaine</p><p className="cos-muted mt-1 text-xs">Votre calendrier éditorial intelligent</p></div><button className="cos-card grid size-9 place-items-center rounded-lg"><Plus className="size-4"/></button></div><div className="grid grid-cols-5 border-t border-[var(--line)]">{["Lun 10","Mar 11","Mer 12","Jeu 13","Ven 14"].map((d,i)=><div className="min-h-40 border-r border-[var(--line)] p-2 last:border-0 sm:p-3"><p className={`text-[10px] ${i===0?"text-violet-500":"cos-muted"}`}>{d}</p>{i!==2&&<div className={`mt-5 rounded-lg p-2 text-[9px] leading-4 sm:text-[10px] ${i===0?"bg-violet-500/12 text-violet-500":"bg-[var(--surface-2)]"}`}>{["Post lancement","Story équipe","","Cas client","Newsletter"][i]}<span className="cos-muted mt-1 hidden sm:block">09:{i}0</span></div>}</div>)}</div></Panel><Panel className="p-5 sm:p-6"><div className="flex items-center justify-between"><p className="font-medium">Activité récente</p><button className="cos-muted text-xs">Tout voir</button></div><div className="mt-5 space-y-5">{[[Check,"Post « Notre nouvelle vision » publié","Il y a 2 h"],[Sparkles,"Suggestion IA ajoutée au planning","Il y a 4 h"],[MessageSquareText,"Camille a commenté un brouillon","Hier"],[TrendingUp,"Bilan hebdomadaire généré","Hier"]].map(([Icon,text,time])=>{const I=Icon as typeof Check;return <div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--surface-2)]"><I className="size-3.5"/></span><div><p className="text-xs leading-5">{text as string}</p><p className="cos-muted mt-0.5 text-[10px]">{time as string}</p></div></div>})}</div></Panel></section>
      </main></div><AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}} className="fixed bottom-5 right-5 z-[90] flex items-center gap-3 rounded-xl bg-zinc-950 px-4 py-3 text-sm text-white shadow-2xl"><span className="grid size-6 place-items-center rounded-full bg-emerald-500"><Check className="size-3"/></span>Proposition ajoutée à votre espace</motion.div>}</AnimatePresence>
  </div>
}
